language: go

branches:
  only:
    - main

addons:
  ssh_known_hosts:
    - github.com

env:
  - HUGO_VERSION=0.82.1

before_install:
  - export TZ='Asia/Shanghai'
  - export LANG="zh_CN.UTF-8"

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -nd -P soft
  - tar -xzvf soft/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -C soft
  - chmod +x soft/hugo
  - export PATH=$PATH:$PWD/soft
  - hugo version  
  - echo 'Hugo engine env is ready.'

script:
  - cd ./exampleSite
  - rm -rf ../public
  - sh ../.travis/replace_params_value.sh
  - hugo -d ../public -t ../..
  - cp ../README.md ../public
  - cp ../README.en.md ../public
  - cp ../LICENSE ../public

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  target-branch: gh-pg
  github-token: $GITHUB_PAGES
  keep-history: true
  commit_message: "Update blog site by TravisCI with build $TRAVIS_BUILD_ID"
  on:
    branch: main

after_deploy:    
  - pwd
  - ls -al ../public
  - echo "Deploy blog article success."