Description = "Weclome to Elkan's blog site that who is best on program develop, pre-sales and big data."
Keywords =  "Blog, Software, Big Data, Product, Architecture, Java, Kylin"
Subtitle = "Don't stop running forward!"
AuthorImg = "/img/avatar.png"
AuthorName = "Elkan.Li"
Introduce = "Never forget your dreamsÔºÅ"
DateFormat = "2006/01/02"
YearFormat = "2006Y"
MonthFormat = "01/02"

ArticleDecContent = "This blog post article is under the <a href='https://creativecommons.org/licenses/by-nc-sa/3.0/' target='_blank' style='text-decoration: underline;'>CC BY-NC-SA 3.0</a> license,Please indicate the source!"

[Footer]
  StorageLink = "https://www.ucloud.cn/"
  StorageName = "UCloud Storage"
  ICPLink = "http://beian.miit.gov.cn"
  ICPNo = "ICP.NO 18047355"

[[Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/elkan1788/"

[[Socials]]
  Name = "ZhiHu"
  Icon = "globe"
  URL = "https://www.zhihu.com/people/fan-meng-xing-chen-1"

[[Links]]
  Name = "Nutz"
  Permalink = "https://nutzam.com/"

[[Links]]
  Name = "JFinal"
  Permalink = "https://jfinal.com/"

[[Links]]
  Name = "Wendal"
  Permalink = "http://wendal.net/"

[[Links]]
  Name = "LiaoXueFeng"
  Permalink = "https://www.liaoxuefeng.com/"