[TagsCloud]
  Enable = true
  Limit = 10

[Share]
  Enable = true
  AddthisId = "Your AddthisId"

[Comment]
  Enable = true
  Module = "Waline"
  LiveReId = "Your LiveReId"
  WalineSerURL = "Your WalineSerURL"

[LeanCloud]
  AppId = "Your LCAppId"
  AppKey = "Your LCAppKey"
  ServerURL = "Your LCServer"

[Statis]
  BusuanziCounter = true
  CNNZSiteId = "Your CNNZSiteId"
  BaiduSiteId = "Your BaiduSiteId"
  GoogleSiteId = "Your GoogleSiteId"

[OnlineIM]
  Enable = true
  DaoVoiceId = "Your DaoVoiceId"

[Others]
  RevolverMapId = "Your RevolverMapId"